#!/usr/bin/env bash
# Run the gateway as native nginx on the host (no Docker).
#
# Renders nginx/templates/default.conf.template into gateway/.run/ with absolute
# host paths + non-root ports, wraps it in a self-contained nginx.conf, validates
# it, and starts (or reloads) nginx. PID lands in gateway/.run/nginx.pid.
#
# Env (all optional):
#   SERVER_NAME       hostname for TLS/redirect          (default localhost)
#   HTTP_PORT         plain-HTTP listen port             (default 8080)
#   HTTPS_PORT        HTTPS listen port                  (default 8443)
#   WEB_UPSTREAM      web host address                   (default 127.0.0.1:3100)
#   RATCHET_UPSTREAM  ratchet backend address            (default 127.0.0.1:3000)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GW_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
GEN_DIR="$GW_DIR/.run"
CERT_DIR="$GW_DIR/certs"
SNIPPET_DIR="$GW_DIR/nginx/snippets"
TEMPLATE="$GW_DIR/nginx/templates/default.conf.template"

SERVER_NAME="${SERVER_NAME:-localhost}"
HTTP_PORT="${HTTP_PORT:-8080}"
HTTPS_PORT="${HTTPS_PORT:-8443}"
WEB_UPSTREAM="${WEB_UPSTREAM:-127.0.0.1:3100}"
RATCHET_UPSTREAM="${RATCHET_UPSTREAM:-127.0.0.1:3000}"

if ! command -v nginx >/dev/null 2>&1; then
  echo "nginx not found on PATH — install it with 'brew install nginx'" >&2
  exit 1
fi
if ! command -v envsubst >/dev/null 2>&1; then
  echo "envsubst not found — install it with 'brew install gettext'" >&2
  exit 1
fi

# Self-signed cert on first run.
if [[ ! -f "$CERT_DIR/fullchain.pem" || ! -f "$CERT_DIR/privkey.pem" ]]; then
  SERVER_NAME="$SERVER_NAME" "$SCRIPT_DIR/gen-certs.sh"
fi

mkdir -p "$GEN_DIR/logs" "$GEN_DIR/tmp"

# Standard ports need no suffix in the redirect; anything else must be explicit
# or the 301 would point at :443 / :80, which native nginx isn't binding.
REDIRECT_HTTPS_PORT=""
[[ "$HTTPS_PORT" != "443" ]] && REDIRECT_HTTPS_PORT=":$HTTPS_PORT"

# Locate mime.types shipped alongside the nginx install.
MIME_TYPES=""
for c in \
  "$(brew --prefix 2>/dev/null)/etc/nginx/mime.types" \
  /opt/homebrew/etc/nginx/mime.types \
  /usr/local/etc/nginx/mime.types \
  /etc/nginx/mime.types; do
  [[ -f "$c" ]] && { MIME_TYPES="$c"; break; }
done

# Render the server block (shared template) with host paths + ports.
SERVER_NAME="$SERVER_NAME" \
WEB_UPSTREAM="$WEB_UPSTREAM" \
RATCHET_UPSTREAM="$RATCHET_UPSTREAM" \
HTTP_LISTEN="$HTTP_PORT" \
HTTPS_LISTEN="$HTTPS_PORT" \
REDIRECT_HTTPS_PORT="$REDIRECT_HTTPS_PORT" \
CERT_DIR="$CERT_DIR" \
SNIPPET_DIR="$SNIPPET_DIR" \
envsubst '${SERVER_NAME} ${WEB_UPSTREAM} ${RATCHET_UPSTREAM} ${HTTP_LISTEN} ${HTTPS_LISTEN} ${REDIRECT_HTTPS_PORT} ${CERT_DIR} ${SNIPPET_DIR}' \
  < "$TEMPLATE" > "$GEN_DIR/server.conf"

# Wrap it in a self-contained top-level config (no system nginx.conf needed).
mime_line="    default_type application/octet-stream;"
[[ -n "$MIME_TYPES" ]] && mime_line="    include $MIME_TYPES;
    default_type application/octet-stream;"

cat > "$GEN_DIR/nginx.conf" <<EOF
# Generated by scripts/run-native.sh — do not edit; edit the template instead.
worker_processes auto;
pid $GEN_DIR/nginx.pid;
error_log $GEN_DIR/logs/error.log warn;

events {
    worker_connections 1024;
}

http {
$mime_line
    access_log $GEN_DIR/logs/access.log;

    client_body_temp_path $GEN_DIR/tmp/client_body;
    proxy_temp_path       $GEN_DIR/tmp/proxy;
    fastcgi_temp_path     $GEN_DIR/tmp/fastcgi;
    uwsgi_temp_path       $GEN_DIR/tmp/uwsgi;
    scgi_temp_path        $GEN_DIR/tmp/scgi;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;

    include $GEN_DIR/server.conf;
}
EOF

# Validate before (re)starting so a bad edit never takes the gateway down.
nginx -t -p "$GEN_DIR" -c "$GEN_DIR/nginx.conf"

pid_file="$GEN_DIR/nginx.pid"
if [[ -f "$pid_file" ]] && kill -0 "$(cat "$pid_file" 2>/dev/null)" 2>/dev/null; then
  echo "[gateway] reloading nginx (pid $(cat "$pid_file"))"
  nginx -p "$GEN_DIR" -c "$GEN_DIR/nginx.conf" -s reload
else
  echo "[gateway] starting nginx on https://$SERVER_NAME:$HTTPS_PORT/"
  nginx -p "$GEN_DIR" -c "$GEN_DIR/nginx.conf"
fi
